### ISSUE TITLE
"maxMPLEsamplesize" argument no longer present in ergm::ergm.pl

### ISSUE THREAD

**Issue by Dreznel** [leifeld/btergm#24]
Hello!

I'm John Carlo Salter with Metrum Research Group. We noticed that this package was removed from CRAN, and we wanted to see if we could help resolve some of the issues.

That being said, I noticed that two of the unit tests are failing because of this deprecated argument. The "maxMPLEsamplesize" argument is present in `btergm.R` on line 307, which is called by two unit tests. This argument was accepted in the 3.10 version of `ergm::ergm.pl`, but is no longer available in the 3.11 version.

**Comment by Dreznel** [comment]
I can confirm that simply removing the argument allows the tests to pass.

Here is a [diff](https://github.com/statnet/ergm/compare/3.10...3.11#diff-90bae6879b0471a15f5a59c844895c712bdb9511407fa5238fe86803ee12eff4L168) of the changes:

(search for `ergm.pl` on the "Files Changed" tab).

**Comment by leifeld** [comment]
Hi John! Thanks for your help here and in the form of the PR. Much appreciated and a welcome surprise! I'm currently overwhelmed with other work at the beginning of the semester due to Corona and haven't found the time to respond to recent `ergm` changes on CRAN. See also #21 and #22 in this context.

If the `ergm.pl` function no longer requires this argument, let's get rid of it here in the code as well.

As a plausibility check, we need to make sure that the results reported in the [JSS article](http://dx.doi.org/10.18637/jss.v083.i06) do not change with any changes we introduce. I think I took some of the examples from the article and translated them into unit tests at some point.

**Comment by leifeld** [comment]
Fixed in #23. Will submit to CRAN over the weekend. Thanks again!
