### ISSUE TITLE
Package ‘btergm’ was removed from the CRAN repository

### ISSUE THREAD

**Issue by Whissi** [leifeld/btergm#34]
From https://cran.r-project.org/web/packages/btergm/index.html:

```
Package ‘btergm’ was removed from the CRAN repository.

Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/btergm).

Archived on 2023-03-31 as requires archived package 'speedglm'.

A summary of the most recent check results can be obtained from the [check results archive](https://cran-archive.r-project.org/web/checks/2023/2023-03-31_check_results_btergm.html).

Please use the canonical form https://cran.r-project.org/package=btergm to link to this page.
```

**Comment by Whissi** [comment]
It was removed because it depends on `speedglm` package which was removed on 2023-04-01 for policy violation.

According to https://github.com/cole-trapnell-lab/monocle3/issues/652#issuecomment-1494760286, maintainer of speedglm package is aware of the problem and package should be back soon.

**Comment by leifeld** [comment]
Thanks. Yes, I was notified by CRAN and given two weeks to remove the `speedglm` dependency. But that was one day after I went on vacation, and when I came back, `btergm` was no longer on CRAN. I'm still working through my email backlog after coming back, but will hopefully get to this problem soon.

**Comment by leifeld** [comment]
I have made `speedglm` optional and resubmitted to CRAN. It should be  there in a few days, but in the meantime, check the new instructions on the [landing page](https://github.com/leifeld/btergm/) for installation details from GitHub. `speedglm` is now used by default if available. If not, the `btergm` function uses `glm` instead, which is slower and takes more memory. To get a faster version, you can also try the argument `usefastglm = TRUE` to use the `fastglm` package for estimation. That's probably the fastest one, though `speedglm` may be more memory-efficient because it can use sparse matrices from the `Matrix` package.
